[package]
name = "rs"
version = "0.1.0"
authors = ["Pawel Perek <pawel@perek.pro>"]
edition = "2018"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["prepush-hook", "run-cargo-test", "run-cargo-clippy", "run-cargo-fmt"]

[dependencies]
