[package]
name = "rs"
version = "0.1.0"
authors = ["Pawel Perek <pawel@perek.pro>"]
edition = "2018"

[dev-dependencies]
cargo-husky = "1"

[dependencies]
enum-as-inner = "0.5.1"
derive_builder = "0.11.2"