use super::{instruction_type::InstructionType, addressing_mode::AddressingMode};

// TODO: I believe size information is unnecessary, because it could be deduced purely from addressing mode. Needs to be researched
pub struct InstructionSignature {
    pub instr_type: InstructionType,
    pub addr_mode: AddressingMode,
    pub size: u8,
    pub cycles: u8,
}

impl InstructionSignature {
    const fn new(instr_type: InstructionType, addr_mode: AddressingMode, size: u8, cycles: u8) -> Self {
        InstructionSignature {
            instr_type,
            addr_mode,
            size,
            cycles,
        }
    }

    pub const fn from_opcode(opcode: u8) -> Self {
        use AddressingMode::*;
        use InstructionType::*;

        //TODO: write byte size and cycles count of instructions
        match opcode {
            0x00 => InstructionSignature::new(Brk, Implied, 1, 7),
            0x01 => InstructionSignature::new(Ora, IndirectX, 2, 6),
            0x02 => InstructionSignature::new(Kil, Implied, 1, 1),
            0x03 => InstructionSignature::new(Slo, IndirectX, 2, 8),
            0x04 => InstructionSignature::new(Nop, ZeroPage, 0, 0),
            0x05 => InstructionSignature::new(Ora, ZeroPage, 0, 0),
            0x06 => InstructionSignature::new(Asl, ZeroPage, 0, 0),
            0x07 => InstructionSignature::new(Slo, ZeroPage, 0, 0),
            0x08 => InstructionSignature::new(Php, Implied, 0, 0),
            0x09 => InstructionSignature::new(Ora, Immediate, 0, 0),
            0x0A => InstructionSignature::new(Asl, Implied, 0, 0),
            0x0B => InstructionSignature::new(Anc, Immediate, 0, 0),
            0x0C => InstructionSignature::new(Nop, Absolute, 0, 0),
            0x0D => InstructionSignature::new(Ora, Absolute, 0, 0),
            0x0E => InstructionSignature::new(Asl, Absolute, 0, 0),
            0x0F => InstructionSignature::new(Slo, Absolute, 0, 0),

            0x10 => InstructionSignature::new(Bpl, Relative, 0, 0),
            0x11 => InstructionSignature::new(Ora, IndirectY, 0, 0),
            0x12 => InstructionSignature::new(Kil, Implied, 0, 0),
            0x13 => InstructionSignature::new(Slo, IndirectY, 0, 0),
            0x14 => InstructionSignature::new(Nop, ZeroPageX, 0, 0),
            0x15 => InstructionSignature::new(Ora, ZeroPageX, 0, 0),
            0x16 => InstructionSignature::new(Asl, ZeroPageX, 0, 0),
            0x17 => InstructionSignature::new(Slo, ZeroPageX, 0, 0),
            0x18 => InstructionSignature::new(Clc, Implied, 0, 0),
            0x19 => InstructionSignature::new(Ora, AbsoluteY, 0, 0),
            0x1A => InstructionSignature::new(Nop, Implied, 0, 0),
            0x1B => InstructionSignature::new(Slo, AbsoluteY, 0, 0),
            0x1C => InstructionSignature::new(Nop, AbsoluteX, 0, 0),
            0x1D => InstructionSignature::new(Ora, AbsoluteX, 0, 0),
            0x1E => InstructionSignature::new(Asl, AbsoluteX, 0, 0),
            0x1F => InstructionSignature::new(Slo, AbsoluteX, 0, 0),

            0x20 => InstructionSignature::new(Jsr, Absolute, 0, 0),
            0x21 => InstructionSignature::new(And, IndirectX, 0, 0),
            0x22 => InstructionSignature::new(Kil, Implied, 0, 0),
            0x23 => InstructionSignature::new(Rla, IndirectX, 0, 0),
            0x24 => InstructionSignature::new(Bit, ZeroPage, 0, 0),
            0x25 => InstructionSignature::new(And, ZeroPage, 0, 0),
            0x26 => InstructionSignature::new(Rol, ZeroPage, 0, 0),
            0x27 => InstructionSignature::new(Rla, ZeroPage, 0, 0),
            0x28 => InstructionSignature::new(Plp, Implied, 0, 0),
            0x29 => InstructionSignature::new(And, Immediate, 0, 0),
            0x2A => InstructionSignature::new(Rol, Implied, 0, 0),
            0x2B => InstructionSignature::new(Anc, Immediate, 0, 0),
            0x2C => InstructionSignature::new(Bit, Absolute, 0, 0),
            0x2D => InstructionSignature::new(And, Absolute, 0, 0),
            0x2E => InstructionSignature::new(Rol, Absolute, 0, 0),
            0x2F => InstructionSignature::new(Rla, Absolute, 0, 0),

            0x30 => InstructionSignature::new(Bmi, Relative, 0, 0),
            0x31 => InstructionSignature::new(And, IndirectY, 0, 0),
            0x32 => InstructionSignature::new(Kil, Implied, 0, 0),
            0x33 => InstructionSignature::new(Rla, IndirectY, 0, 0),
            0x34 => InstructionSignature::new(Nop, ZeroPageX, 0, 0),
            0x35 => InstructionSignature::new(And, ZeroPageX, 0, 0),
            0x36 => InstructionSignature::new(Rol, ZeroPageX, 0, 0),
            0x37 => InstructionSignature::new(Rla, ZeroPageX, 0, 0),
            0x38 => InstructionSignature::new(Sec, Implied, 0, 0),
            0x39 => InstructionSignature::new(And, AbsoluteY, 0, 0),
            0x3A => InstructionSignature::new(Nop, Implied, 0, 0),
            0x3B => InstructionSignature::new(Rla, AbsoluteY, 0, 0),
            0x3C => InstructionSignature::new(Nop, AbsoluteX, 0, 0),
            0x3D => InstructionSignature::new(And, AbsoluteX, 0, 0),
            0x3E => InstructionSignature::new(Rol, AbsoluteX, 0, 0),
            0x3F => InstructionSignature::new(Rla, AbsoluteX, 0, 0),

            0x40 => InstructionSignature::new(Rti, Implied, 0, 0),
            0x41 => InstructionSignature::new(Eor, IndirectX, 0, 0),
            0x42 => InstructionSignature::new(Kil, Implied, 0, 0),
            0x43 => InstructionSignature::new(Sre, IndirectX, 0, 0),
            0x44 => InstructionSignature::new(Nop, ZeroPage, 0, 0),
            0x45 => InstructionSignature::new(Eor, ZeroPage, 0, 0),
            0x46 => InstructionSignature::new(Lsr, ZeroPage, 0, 0),
            0x47 => InstructionSignature::new(Sre, ZeroPage, 0, 0),
            0x48 => InstructionSignature::new(Pha, Implied, 0, 0),
            0x49 => InstructionSignature::new(Eor, Immediate, 0, 0),
            0x4A => InstructionSignature::new(Lsr, Implied, 0, 0),
            0x4B => InstructionSignature::new(Alr, Immediate, 0, 0),
            0x4C => InstructionSignature::new(Jmp, Absolute, 0, 0),
            0x4D => InstructionSignature::new(Eor, Absolute, 0, 0),
            0x4E => InstructionSignature::new(Lsr, Absolute, 0, 0),
            0x4F => InstructionSignature::new(Sre, Absolute, 0, 0),

            0x50 => InstructionSignature::new(Bvc, Relative, 0, 0),
            0x51 => InstructionSignature::new(Eor, IndirectY, 0, 0),
            0x52 => InstructionSignature::new(Kil, Implied, 0, 0),
            0x53 => InstructionSignature::new(Sre, IndirectY, 0, 0),
            0x54 => InstructionSignature::new(Nop, ZeroPageX, 0, 0),
            0x55 => InstructionSignature::new(Eor, ZeroPageX, 0, 0),
            0x56 => InstructionSignature::new(Lsr, ZeroPageX, 0, 0),
            0x57 => InstructionSignature::new(Sre, ZeroPageX, 0, 0),
            0x58 => InstructionSignature::new(Cli, Implied, 0, 0),
            0x59 => InstructionSignature::new(Eor, AbsoluteY, 0, 0),
            0x5A => InstructionSignature::new(Nop, Implied, 0, 0),
            0x5B => InstructionSignature::new(Sre, AbsoluteY, 0, 0),
            0x5C => InstructionSignature::new(Nop, AbsoluteX, 0, 0),
            0x5D => InstructionSignature::new(Eor, AbsoluteX, 0, 0),
            0x5E => InstructionSignature::new(Lsr, AbsoluteX, 0, 0),
            0x5F => InstructionSignature::new(Sre, AbsoluteX, 0, 0),

            0x60 => InstructionSignature::new(Rts, Implied, 0, 0),
            0x61 => InstructionSignature::new(Adc, IndirectX, 0, 0),
            0x62 => InstructionSignature::new(Kil, Implied, 0, 0),
            0x63 => InstructionSignature::new(Rra, IndirectX, 0, 0),
            0x64 => InstructionSignature::new(Nop, ZeroPage, 0, 0),
            0x65 => InstructionSignature::new(Adc, ZeroPage, 0, 0),
            0x66 => InstructionSignature::new(Ror, ZeroPage, 0, 0),
            0x67 => InstructionSignature::new(Rra, ZeroPage, 0, 0),
            0x68 => InstructionSignature::new(Pla, Implied, 0, 0),
            0x69 => InstructionSignature::new(Adc, Immediate, 0, 0),
            0x6A => InstructionSignature::new(Ror, Implied, 0, 0),
            0x6B => InstructionSignature::new(Arr, Immediate, 0, 0),
            0x6C => InstructionSignature::new(Jmp, Indirect, 0, 0),
            0x6D => InstructionSignature::new(Adc, Absolute, 0, 0),
            0x6E => InstructionSignature::new(Ror, Absolute, 0, 0),
            0x6F => InstructionSignature::new(Rra, Absolute, 0, 0),

            0x70 => InstructionSignature::new(Bvs, Relative, 0, 0),
            0x71 => InstructionSignature::new(Adc, IndirectY, 0, 0),
            0x72 => InstructionSignature::new(Kil, Implied, 0, 0),
            0x73 => InstructionSignature::new(Rra, IndirectY, 0, 0),
            0x74 => InstructionSignature::new(Nop, ZeroPageX, 0, 0),
            0x75 => InstructionSignature::new(Adc, ZeroPageX, 0, 0),
            0x76 => InstructionSignature::new(Ror, ZeroPageX, 0, 0),
            0x77 => InstructionSignature::new(Rra, ZeroPageX, 0, 0),
            0x78 => InstructionSignature::new(Sei, Implied, 0, 0),
            0x79 => InstructionSignature::new(Adc, AbsoluteY, 0, 0),
            0x7A => InstructionSignature::new(Nop, Implied, 0, 0),
            0x7B => InstructionSignature::new(Rra, AbsoluteY, 0, 0),
            0x7C => InstructionSignature::new(Nop, AbsoluteX, 0, 0),
            0x7D => InstructionSignature::new(Adc, AbsoluteX, 0, 0),
            0x7E => InstructionSignature::new(Ror, AbsoluteX, 0, 0),
            0x7F => InstructionSignature::new(Rra, AbsoluteX, 0, 0),

            0x80 => InstructionSignature::new(Nop, Immediate, 0, 0),
            0x81 => InstructionSignature::new(Sta, IndirectX, 0, 0),
            0x82 => InstructionSignature::new(Nop, Immediate, 0, 0),
            0x83 => InstructionSignature::new(Sax, IndirectX, 0, 0),
            0x84 => InstructionSignature::new(Sty, ZeroPage, 0, 0),
            0x85 => InstructionSignature::new(Sta, ZeroPage, 0, 0),
            0x86 => InstructionSignature::new(Stx, ZeroPage, 0, 0),
            0x87 => InstructionSignature::new(Sax, ZeroPage, 0, 0),
            0x88 => InstructionSignature::new(Dey, Implied, 0, 0),
            0x89 => InstructionSignature::new(Nop, Immediate, 0, 0),
            0x8A => InstructionSignature::new(Txa, Implied, 0, 0),
            0x8B => InstructionSignature::new(Xaa, Immediate, 0, 0),
            0x8C => InstructionSignature::new(Sty, Absolute, 0, 0),
            0x8D => InstructionSignature::new(Sta, Absolute, 0, 0),
            0x8E => InstructionSignature::new(Stx, Absolute, 0, 0),
            0x8F => InstructionSignature::new(Sax, Absolute, 0, 0),

            0x90 => InstructionSignature::new(Bcc, Relative, 0, 0),
            0x91 => InstructionSignature::new(Sta, IndirectY, 0, 0),
            0x92 => InstructionSignature::new(Kil, Implied, 0, 0),
            0x93 => InstructionSignature::new(Ahx, IndirectY, 0, 0),
            0x94 => InstructionSignature::new(Sty, ZeroPageX, 0, 0),
            0x95 => InstructionSignature::new(Sta, ZeroPageX, 0, 0),
            0x96 => InstructionSignature::new(Stx, ZeroPageY, 0, 0),
            0x97 => InstructionSignature::new(Sax, ZeroPageY, 0, 0),
            0x98 => InstructionSignature::new(Tya, Implied, 0, 0),
            0x99 => InstructionSignature::new(Sta, AbsoluteY, 0, 0),
            0x9A => InstructionSignature::new(Txs, Implied, 0, 0),
            0x9B => InstructionSignature::new(Tas, AbsoluteY, 0, 0),
            0x9C => InstructionSignature::new(Shy, AbsoluteX, 0, 0),
            0x9D => InstructionSignature::new(Sta, AbsoluteX, 0, 0),
            0x9E => InstructionSignature::new(Shx, AbsoluteY, 0, 0),
            0x9F => InstructionSignature::new(Ahx, AbsoluteY, 0, 0),

            0xA0 => InstructionSignature::new(Ldy, Immediate, 0, 0),
            0xA1 => InstructionSignature::new(Lda, IndirectX, 0, 0),
            0xA2 => InstructionSignature::new(Ldx, Immediate, 0, 0),
            0xA3 => InstructionSignature::new(Lax, IndirectX, 0, 0),
            0xA4 => InstructionSignature::new(Ldy, ZeroPage, 0, 0),
            0xA5 => InstructionSignature::new(Lda, ZeroPage, 0, 0),
            0xA6 => InstructionSignature::new(Ldx, ZeroPage, 0, 0),
            0xA7 => InstructionSignature::new(Lax, ZeroPage, 0, 0),
            0xA8 => InstructionSignature::new(Tay, Implied, 0, 0),
            0xA9 => InstructionSignature::new(Lda, Immediate, 0, 0),
            0xAA => InstructionSignature::new(Tax, Implied, 0, 0),
            0xAB => InstructionSignature::new(Lax, Immediate, 0, 0),
            0xAC => InstructionSignature::new(Ldy, Absolute, 0, 0),
            0xAD => InstructionSignature::new(Lda, Absolute, 0, 0),
            0xAE => InstructionSignature::new(Ldx, Absolute, 0, 0),
            0xAF => InstructionSignature::new(Lax, Absolute, 0, 0),

            0xB0 => InstructionSignature::new(Bcs, Relative, 0, 0),
            0xB1 => InstructionSignature::new(Lda, IndirectY, 0, 0),
            0xB2 => InstructionSignature::new(Kil, Implied, 0, 0),
            0xB3 => InstructionSignature::new(Lax, IndirectY, 0, 0),
            0xB4 => InstructionSignature::new(Ldy, ZeroPageX, 0, 0),
            0xB5 => InstructionSignature::new(Lda, ZeroPageX, 0, 0),
            0xB6 => InstructionSignature::new(Ldx, ZeroPageY, 0, 0),
            0xB7 => InstructionSignature::new(Lax, ZeroPageY, 0, 0),
            0xB8 => InstructionSignature::new(Clv, Implied, 0, 0),
            0xB9 => InstructionSignature::new(Lda, AbsoluteY, 0, 0),
            0xBA => InstructionSignature::new(Tsx, Implied, 0, 0),
            0xBB => InstructionSignature::new(Las, AbsoluteY, 0, 0),
            0xBC => InstructionSignature::new(Ldy, AbsoluteX, 0, 0),
            0xBD => InstructionSignature::new(Lda, AbsoluteX, 0, 0),
            0xBE => InstructionSignature::new(Ldx, AbsoluteY, 0, 0),
            0xBF => InstructionSignature::new(Lax, AbsoluteY, 0, 0),

            0xC0 => InstructionSignature::new(Cpy, Immediate, 0, 0),
            0xC1 => InstructionSignature::new(Cmp, IndirectX, 0, 0),
            0xC2 => InstructionSignature::new(Nop, Immediate, 0, 0),
            0xC3 => InstructionSignature::new(Dcp, IndirectX, 0, 0),
            0xC4 => InstructionSignature::new(Cpy, ZeroPage, 0, 0),
            0xC5 => InstructionSignature::new(Cmp, ZeroPage, 0, 0),
            0xC6 => InstructionSignature::new(Dec, ZeroPage, 0, 0),
            0xC7 => InstructionSignature::new(Dcp, ZeroPage, 0, 0),
            0xC8 => InstructionSignature::new(Iny, Implied, 0, 0),
            0xC9 => InstructionSignature::new(Cmp, Immediate, 0, 0),
            0xCA => InstructionSignature::new(Dex, Implied, 0, 0),
            0xCB => InstructionSignature::new(Axs, Immediate, 0, 0),
            0xCC => InstructionSignature::new(Cpy, Absolute, 0, 0),
            0xCD => InstructionSignature::new(Cmp, Absolute, 0, 0),
            0xCE => InstructionSignature::new(Dec, Absolute, 0, 0),
            0xCF => InstructionSignature::new(Dcp, Absolute, 0, 0),

            0xD0 => InstructionSignature::new(Bne, Relative, 0, 0),
            0xD1 => InstructionSignature::new(Cmp, IndirectY, 0, 0),
            0xD2 => InstructionSignature::new(Kil, Implied, 0, 0),
            0xD3 => InstructionSignature::new(Dcp, IndirectY, 0, 0),
            0xD4 => InstructionSignature::new(Nop, ZeroPageX, 0, 0),
            0xD5 => InstructionSignature::new(Cmp, ZeroPageX, 0, 0),
            0xD6 => InstructionSignature::new(Dec, ZeroPageX, 0, 0),
            0xD7 => InstructionSignature::new(Dcp, ZeroPageX, 0, 0),
            0xD8 => InstructionSignature::new(Cld, Implied, 0, 0),
            0xD9 => InstructionSignature::new(Cmp, AbsoluteY, 0, 0),
            0xDA => InstructionSignature::new(Nop, Implied, 0, 0),
            0xDB => InstructionSignature::new(Dcp, AbsoluteY, 0, 0),
            0xDC => InstructionSignature::new(Nop, AbsoluteX, 0, 0),
            0xDD => InstructionSignature::new(Cmp, AbsoluteX, 0, 0),
            0xDE => InstructionSignature::new(Dec, AbsoluteX, 0, 0),
            0xDF => InstructionSignature::new(Dcp, AbsoluteX, 0, 0),

            0xE0 => InstructionSignature::new(Cpx, Immediate, 0, 0),
            0xE1 => InstructionSignature::new(Sbc, IndirectX, 0, 0),
            0xE2 => InstructionSignature::new(Nop, Immediate, 0, 0),
            0xE3 => InstructionSignature::new(Isc, IndirectX, 0, 0),
            0xE4 => InstructionSignature::new(Cpx, ZeroPage, 0, 0),
            0xE5 => InstructionSignature::new(Sbc, ZeroPage, 0, 0),
            0xE6 => InstructionSignature::new(Inc, ZeroPage, 0, 0),
            0xE7 => InstructionSignature::new(Isc, ZeroPage, 0, 0),
            0xE8 => InstructionSignature::new(Inx, Implied, 0, 0),
            0xE9 => InstructionSignature::new(Sbc, Immediate, 0, 0),
            0xEA => InstructionSignature::new(Nop, Implied, 0, 0),
            0xEB => InstructionSignature::new(Sbc, Immediate, 0, 0),
            0xEC => InstructionSignature::new(Cpx, Absolute, 0, 0),
            0xED => InstructionSignature::new(Sbc, Absolute, 0, 0),
            0xEE => InstructionSignature::new(Inc, Absolute, 0, 0),
            0xEF => InstructionSignature::new(Isc, Absolute, 0, 0),

            0xF0 => InstructionSignature::new(Beq, Relative, 0, 0),
            0xF1 => InstructionSignature::new(Sbc, IndirectY, 0, 0),
            0xF2 => InstructionSignature::new(Kil, Implied, 0, 0),
            0xF3 => InstructionSignature::new(Isc, IndirectY, 0, 0),
            0xF4 => InstructionSignature::new(Nop, ZeroPageX, 0, 0),
            0xF5 => InstructionSignature::new(Sbc, ZeroPageX, 0, 0),
            0xF6 => InstructionSignature::new(Inc, ZeroPageX, 0, 0),
            0xF7 => InstructionSignature::new(Isc, ZeroPageX, 0, 0),
            0xF8 => InstructionSignature::new(Sed, Implied, 0, 0),
            0xF9 => InstructionSignature::new(Sbc, AbsoluteY, 0, 0),
            0xFA => InstructionSignature::new(Nop, Implied, 0, 0),
            0xFB => InstructionSignature::new(Isc, AbsoluteY, 0, 0),
            0xFC => InstructionSignature::new(Nop, AbsoluteX, 0, 0),
            0xFD => InstructionSignature::new(Sbc, AbsoluteX, 0, 0),
            0xFE => InstructionSignature::new(Inc, AbsoluteX, 0, 0),
            0xFF => InstructionSignature::new(Isc, AbsoluteX, 0, 0),
        }
    }
}



